### ISSUE TITLE
About version 1.0

### ISSUE THREAD

**Issue by doabit** [doabit/semantic-ui-sass#31]
I have worked on it last week, but thiere are a lot of problems, now, the biggest is 

```
Incompatible units: '%' and 'em'.
```

Sass doesn't support like this

``` css
$largeMonitorWidth: 50%;
$largeMonitorMargin: 0em 0em 0em -($largeMonitorWidth / 2);
```

OR

```
$closeHitBoxOffset: 1.3em;
$closePadding: $closeHitBoxOffset 0em 0em 0em;
```

I have modified lots of files, but it would difficult to update if use this method, i haven't found a good method to solve the problem. If anybody have an idea, welcome PR, thanks.

**Comment by frankis** [comment]
Maybe this converter can make this happen?
https://github.com/RealtyPremium/Semantic-UI-SCSS

**Comment by doabit** [comment]
@frankis The is no way now because of sass doesn't support some features.

**Comment by NilAndNull** [comment]
The only way to workaround this is using scripting. 

If you use only rails, you could use scss.erb files, but I think you don't want that, since this is a SASS port, not a mandatory rails port. 

So you can have some kind of script, that takes the original semantic-ui files as input and return scss files as output, with the replacement you need, so it automates the migration process.

I'm currently using Bootstrap (which sucks), but semantic-ui-sass with no global variables it's a no no for me. Variables are the base of usefulness of SASS and it's one of the most powerful features of semantic-ui. 

I wish you would have global variables, that you allow me to use Semantic UI in my rails projects, which unfortunately is not currently possible :/
