### ISSUE TITLE
assets size is big

### ISSUE THREAD

**Issue by citysheep** [doabit/semantic-ui-sass#42]
I am building a Rails application using this library, and I found that the compiled assets is bit too big (2MB). Is there anyway to minimize the complied asset size? Maybe only include components I am using? Thanks.

**Comment by klaseskilson** [comment]
Since you're using Rails, its really simple to only include the modules you use. The instructions are in [README.md](https://github.com/doabit/semantic-ui-sass/blob/7bc470190e22adf874fd7458387697628ca6b87f/README.md#semantic-ui-sass-with-rails).

In your main scss file (usually application.scss), you replace

```sass
@import "semantic-ui";
```
with
```sass
@import "semantic-ui/collections/menu";
```

Replace  `collections/menu` with whatever module you want.

The same goes for javascript. Replace

```js
// Loads all Semantic javascripts
//= require semantic-ui
```
with
```js
//= require semantic-ui/modal
```

Again, replace `modal` with what you're after.

**Comment by citysheep** [comment]
thanks very much!
